@Api_HostAddress = http://localhost:5266/tiki
@OrderCode = 883195198


### Orders
GET {{Api_HostAddress}}/orders
Accept: application/json

###
GET {{Api_HostAddress}}/order/{{OrderCode}}
Accept: application/json
