@Api_HostAddress = http://localhost:5266/lazada
@OrderId = 514237118924226
@ProductId = 3136220399

### Products
GET {{Api_HostAddress}}/products
Accept: application/json

###
GET {{Api_HostAddress}}/product/{{ProductId}}
Accept: application/json

###
GET {{Api_HostAddress}}/product/update_stock?itemId=1969963007&skuId=9099096798&sellerSku="212429"&stock=1
Accept: application/json

### Orders
GET {{Api_HostAddress}}/orders
Accept: application/json

###
GET {{Api_HostAddress}}/order/{{OrderId}}
Accept: application/json

###
POST {{Api_HostAddress}}/order/get_document
Accept: application/json
Content-Type: application/json
[ "513512508415615" ]
