@Api_HostAddress = http://localhost:5266/lazada
@OrderId = 250404DFDFH0E7
@ProductId = 5120130578

### Products
GET {{Api_HostAddress}}/products
Accept: application/json

###
GET {{Api_HostAddress}}/product/{{ProductId}}
Accept: application/json

### Orders
GET {{Api_HostAddress}}/orders
Accept: application/json

###
GET {{Api_HostAddress}}/order/{{OrderId}}
Accept: application/json
